export default [
    {
        id: 1,
        title:"Gourd Grin ",
        description: "The artist knew they were going to keep up with inktober this year",
        src: 'https://pbs.twimg.com/media/FAmkdEWX0BUn4xZ?format=jpg&name=small',
    },
    {
        id: 2,
        title:"Bashful Bowser",
        description: "Bowser took to the heat, and now he spreads the lava gospel",
        src: 'https://pbs.twimg.com/media/FAvpuhhXEAMdCNs?format=jpg&name=small',
    }, {
        id: 3,
        title:"Lurkin at you",
        description: "Someone's got a crush",
        src: 'https://pbs.twimg.com/media/FA0wJ39WUAgnERd?format=png&name=small',
    }, {
        id: 4,
        title:"4 eyes",
        description: "Kid's say the darndest  things, but sometimes they just look at you..menacingly",
        src: 'https://pbs.twimg.com/media/FA6Cn9QXMAo7tsm?format=jpg&name=360x360',
    },
    {
        id: 5,
        title:"Staying *ahead*",
        description: "It's that feeling of submerging yourself underwater as a kid, and pretending you're a killer, except now you are",
        src: 'https://pbs.twimg.com/media/FA-7VZbVcAM6-uR?format=png&name=360x360',
    },
    {
        id: 6,
        title:"No quema cuh",
        description: "It's a life style choice",
        src: 'https://pbs.twimg.com/media/FBEV8YcXsAANPje?format=jpg&name=small',
    },
    {
        id: 7,
        title:"Mouth noises",
        description: "giaooo-gug-gug-gug",
        src: 'https://pbs.twimg.com/media/FBJRyoBXsCgP7l3?format=jpg&name=900x900',
    },
    {
        id: 8,
        title:"Chronically Online",
        description: "That discord mod who would stab you for making an among us joke",
        src: 'https://pbs.twimg.com/media/FBOetxhX0AMKNEI?format=jpg&name=medium',
    },
    {
        id: 9,
        title:"Twas a Torso",
        description: "This creature navigates the world using their eye sockets to swing around",
        src: 'https://pbs.twimg.com/media/FBS9H_iXoAQ1rAa?format=jpg&name=medium',
    },
    {
        id: 10,
        title:"MiMic",
        description: "They just like causing a lil' mischief and we should let them",
        src: 'https://pbs.twimg.com/media/FBY7FbnXoAE5np5?format=png&name=900x900',
    },
    {
        id: 11,
        title:"Inspiration Idol",
        description: "You ever been an influencer and a murderer? There can be only one",
        src: 'https://pbs.twimg.com/media/FBeChpMWYAEPYiQ?format=jpg&name=medium',
    },
    {
        id: 12,
        title:"Candy Cutie",
        description: "Those teeth actually kill, and the appearance is a facade RUN",
        src: 'https://pbs.twimg.com/media/FBi2ItBWUAIQtj7?format=jpg&name=4096x4096',
    },
    {
        id: 13,
        title:"Cursed Cuttlefish",
        description: "It's dainty hands help remove your teeth while you sleep :)",
        src: 'https://pbs.twimg.com/media/FBoUk7VX0AIuL4i?format=jpg&name=medium',
    },
    {
        id: 14,
        title:"Open Wide MF",
        description: "Homage to the Classics",
        src: 'https://pbs.twimg.com/media/FBrXcedWQAQp9bN?format=jpg&name=medium',
    },
    {
        id: 15,
        title:"Babooshka",
        description: "Siri play Kate Bush's Babooshka",
        src: 'https://pbs.twimg.com/media/FBwvkwBWYAMbixW?format=jpg&name=large',
    },
    {
        id: 16,
        title:"A Spider's Purpose",
        description: "Watch as spiders lay their eggs in someone's anal cavity, truly horrific",
        src: 'https://pbs.twimg.com/media/FB10S5zXMAAuao6?format=jpg&name=medium',
    },
    {
        id: 17,
        title:"Peace Amongst Friends",
        description: "Creatures hangout too",
        src: 'https://pbs.twimg.com/media/FB72LhzXoAMUWsE?format=jpg&name=large',
    },
    {
        id: 18,
        title:"Angel's are Assholes",
        description: "Talk about being in the wrong place at the wrong time",
        src: 'https://pbs.twimg.com/media/FCCFaEoX0AU9cp_?format=jpg&name=medium',
    },
    {
        id: 19,
        title:"Lean, Mean, AND GREEN",
        description: "What's a Pumpkin to do except collect some more body parts",
        src: 'https://pbs.twimg.com/media/FCHRtxKVQAAzlNr?format=jpg&name=360x360',
    },
    {
        id: 20,
        title:"Timid, and Tiny",
        description: "ITS HIS FIRST DAY GO EASY ON HIM, hes got 29 friends who could kick your ass",
        src: 'https://pbs.twimg.com/media/FCMajEVWQAEoQbn?format=jpg&name=medium',
    },
    {
        id: 21,
        title:"Angry Bitch",
        description: "If you've ever tossed one of his friends at some pig bastards, he's coming for you",
        src: 'https://pbs.twimg.com/media/FCRlZ1pX0AMWh7u?format=jpg&name=medium',
    },
    {
        id: 22,
        title:"The Unsung Hero",
        description: "If you've ever been mildly inconvenienced by an overlord, YOUR WELCOME",
        src: 'https://pbs.twimg.com/media/FCWwS0YX0AUU6Qa?format=jpg&name=medium',
    },
    {
        id: 23,
        title:"Being Human",
        description: "Can't escape human emotions",
        src: 'https://pbs.twimg.com/media/FCcVTD0WQAUwKiN?format=jpg&name=medium',
    },
    {
        id: 24,
        title:"No more Monkeys",
        description: 'Mama called the doctor and the doctor said "HELP ME HES EATING MY EYES" ',
        src: 'https://pbs.twimg.com/media/FCg_bvGXIAIkVnr?format=jpg&name=medium',
    },
    {
        id: 25,
        title:"The Insatiable Ankha",
        description: "Looks like you're next",
        src: 'https://pbs.twimg.com/media/FCmWr7zXIAMT2B_?format=jpg&name=medium',
    },
    {
        id: 26,
        title:"BOOOO in D-minor",
        description: "Whistles a hauntingly beautiful melody for those about to die, do you hear that?",
        src: 'https://pbs.twimg.com/media/FCrmyfoXMAUw4h7?format=jpg&name=900x900',
    },
    {
        id: 27,
        title:"Knotty girls end up dead",
        description: "Bumped into this one recently, she won't let me go",
        src: 'https://pbs.twimg.com/media/FCsv22AWEAMFOtn?format=png&name=medium',
    },
    {
        id: 28,
        title:"Death by Heartache",
        description: "The story of a poor sucker who won't rest until their greatest love is dead... so no one else can have them",
        src: 'https://pbs.twimg.com/media/FC2BtaIVEAE9-xR?format=png&name=medium',
    },
    {
        id: 29,
        title:"Turn Away",
        description: "Run runr rujnrujr run rurnf ru r",
        src: 'https://pbs.twimg.com/media/FC7kJqQX0AARMDc?format=jpg&name=large',
    },
    {
        id: 30,
        title:"Our Riddles Three",
        description: "1. What's dead, and should have minded it's own business? 2.What's behind you, and ready 3.I'm the uncreative one, your life is over bitch",
        src: 'https://pbs.twimg.com/media/FDBXpGVWUAUgFAY?format=jpg&name=large',
    },
    {
        id: 31,
        title:"Beauty Beheads",
        description: "Okay but if it brings her more joy to kill you, why wouldn't you just let her do it?",
        src: 'https://pbs.twimg.com/media/FDEvo2SWUAY1g_p?format=png&name=4096x4096',
    },
]